### PR TITLE
Add Travis CI and fix rubocop

### PR DESCRIPTION
**Pull request by nicolasleger**

### CODE REVIEW

**Comment by emad-elsaid** [comment]
Thanks Nicolas for that 👍

**Comment by nicolasleger** [comment]
@emad-elsaid You have to setup Travis on the official repo since you are admin.
You could also add the test master branch badge then in ReadMe.

**Comment by emad-elsaid** [comment]
I have just done that minutes ago

**Comment by nicolasleger** [comment]
Excellent 👍

**Pull request merged**
